# Generated by Django 4.1.3 on 2023-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='images'),
        ),
    ]
